<?php
/**
 * Certificate Print Template
 *
 * Print-optimized certificate template for browser printing
 * Now uses the unified Certificate HTML Generator for consistency.
 *
 * @package SkillPulse_LMS
 * @subpackage Templates/Certificates
 * @version 1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

// Get certificate data from globals (set by certificate handler).
$user_id   = isset( $GLOBALS['splms_certificate_user_id'] ) ? absint( $GLOBALS['splms_certificate_user_id'] ) : get_current_user_id();
$course_id = isset( $GLOBALS['splms_certificate_course_id'] ) ? absint( $GLOBALS['splms_certificate_course_id'] ) : 0;

// Security validation: Basic data validation.
if ( ! $user_id || ! $course_id ) {
	wp_die( esc_html__( 'Invalid certificate request.', 'skillpulse-lms' ) );
}

// Security validation: Ensure current user can print this certificate.
$current_user_id = get_current_user_id();
if ( $current_user_id && $current_user_id !== $user_id ) {
	// Allow admins to print any certificate.
	if ( ! current_user_can( 'manage_options' ) ) {
		wp_die( esc_html__( 'You are not authorized to print this certificate.', 'skillpulse-lms' ) );
	}
}

// Get user and course data.
$user   = get_userdata( $user_id );
$course = get_post( $course_id );

if ( ! $user || ! $course ) {
	wp_die( esc_html__( 'Invalid user or course data.', 'skillpulse-lms' ) );
}

// Security validation: Verify user actually has this certificate.
$simple_certificates = SkillPulse_LMS_Certificates::get_instance();
if ( ! $simple_certificates->user_has_certificate( $user_id, $course_id ) ) {
	wp_die( esc_html__( 'Certificate not found or not authorized.', 'skillpulse-lms' ) );
}

// Get certificate template ID.
$certificate_id = get_the_ID();

// Generate certificate content using unified HTML generator.
$certificate_content = '';
if ( class_exists( 'SkillPulse_LMS_Certificate_HTML_Generator' ) ) {
	$certificate_content = SkillPulse_LMS_Certificate_HTML_Generator::generate_certificate_html(
		$certificate_id,
		array(
			'user_id'     => $user_id,
			'course_id'   => $course_id,
			'context'     => 'print',
			'include_css' => true,
		)
	);
}

?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title><?php echo esc_html( get_the_title() ); ?> - <?php echo esc_html( $user->display_name ); ?></title>
	<style>
		/* Enhanced Print Page Setup */
		@page {
			size: A4 landscape;
			margin: 10mm;
		}

		* {
			margin: 0;
			padding: 0;
			box-sizing: border-box;
		}

		body {
			font-family: 'Georgia', serif;
			background-color: #ffffff;
			width: 100vw;
			height: 100vh;
			display: flex;
			align-items: center;
			justify-content: center;
			line-height: 1.4;
		}

		.print-container {
			width: 100%;
			height: 100%;
			display: flex;
			align-items: center;
			justify-content: center;
		}

		/* Additional print-specific styles */
		@media print {
			body {
				margin: 0 !important;
				padding: 0 !important;
				background: white !important;
				-webkit-print-color-adjust: exact;
				color-adjust: exact;
			}

			.print-container {
				width: 100% !important;
				height: 100% !important;
				margin: 0 !important;
				padding: 0 !important;
			}

			/* Ensure colors are preserved */
			* {
				-webkit-print-color-adjust: exact !important;
				color-adjust: exact !important;
			}
		}
	</style>
</head>
<body>
	<div class="print-container">
		<?php if ( ! empty( $certificate_content ) ) : ?>
			<?php
			// Output certificate content directly since it's generated by our own system.
			echo $certificate_content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
			?>
		<?php else : ?>
			<div style="text-align: center; padding: 2rem; color: #dc3545; border: 1px solid #dc3545; background: #f8d7da; border-radius: 5px;">
				<p><?php esc_html_e( 'Certificate could not be generated.', 'skillpulse-lms' ); ?></p>
			</div>
		<?php endif; ?>
	</div>
</body>
</html>